version: 2.1

executors:
  my-executor:
    docker:
      - image: cimg/base:stable
    #     auth:
    #       username: mydockerhub-user
    #       password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    #working_directory: /tmp

jobs:
  flow:
    executor: my-executor
    steps:
      - checkout
      - run: mkdir -p workspace
      - run: echo "Hello, world!" > workspace/echo-output
      - run:
          name: Add back-end ip to ansible inventory
          command: |
            INV=".circleci/ansible/inventory.txt"
            echo "[web]" > $INV
            echo "HELLOOOOOO" >> $INV
            tail $INV

      # Persist the specified paths (workspace/echo-output) into the workspace for use in downstream job.
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory. This is a directory on the container which is
          # taken to be the root directory of the workspace.
          root: ~/
          # Must be relative path from root
          paths:
            - project/.circleci/ansible/inventory.txt

  downstream:
    executor: my-executor
    steps:
      - checkout
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: /tmp/project/.circleci/ansible/

      - run:
          name: "Load"
          command: |
            #
            INV=".circleci/ansible/inventory.txt"
            tail $INV
          # if [[ `cat /tmp/workspace/echo-output` == "Hello, world!" ]]; then
          #   echo "It worked!";
          # else
          #   echo "Nope!"; exit 1
          # fi
      - run:
          name: "Load2"
          command: |
            ls /tmp
            ls /tmp/project
            ls /tmp/project/.crcleci
            ls /tmp/project/.crcleci/ansible
            ls ~/project
            INV="/tmp/project/.circleci/ansible/inventory.txt"
            tail $INV
          # if [[ `cat /tmp/workspace/echo-output` == "Hello, world!" ]]; then
          #   echo "It worked!";
          # else
          #   echo "Nope!"; exit 1
          # fi

workflows:
  btd:
    jobs:
      - flow
      - downstream:
          requires:
            - flow


# VS Code Extension Version: 1.4.0
